// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionsDelta } from './ConnectionsDelta'
import type { ConnectionsSnapshot } from './ConnectionsSnapshot'

export type ConnectionMessage =
  | { type: 'snapshot'; data: ConnectionsSnapshot }
  | { type: 'delta'; data: ConnectionsDelta }
