// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Connection } from './Connection'

export type ConnectionsDelta = {
  epochId: string
  sequenceId: number
  downloadTotal: number
  uploadTotal: number
  memory: number
  added: Array<Connection>
  updated: Array<string | number>
  removed: Array<string>
}
