// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Connection } from './Connection'

export type ConnectionsSnapshot = {
  epochId: string
  sequenceId: number
  downloadTotal: number
  uploadTotal: number
  connections: Array<Connection>
  memory: number
}
